### ISSUE TITLE
Add tls - allow_unencrypted_doh

### ISSUE THREAD

**Issue by durandguru** [gmichels/terraform-provider-adguard#106]
Can you add allow_unencrypted_doh  under tls? It is a boolean.

Thanks

**Comment by gmichels** [comment]
Upstream doesn't currently support it being set via the API, it has to be done manually in the config file. See https://github.com/AdguardTeam/AdGuardHome/issues/7040

I wouldn't get my hopes up, though, also see https://github.com/AdguardTeam/AdGuardHome/issues/1009#issuecomment-853947044. Which is a pity, because I also would welcome having that ability.

If they ever add support for it, I will surely have it implemented here as well.
