### ISSUE TITLE
adguard_client last_updated triggers update

### ISSUE THREAD

**Issue by durandguru** [gmichels/terraform-provider-adguard#108]
I have set some clients with adguard_client. An plan will generate a change because last_updated triggers the change. This will not happen directly after an apply, it takes some time for an plan to show this update again. So a plan directly after an apply does not show something to update. I do not know the timeframe but certainly a day later the plan show something to update,

 # adguard_client.ina-vlan-30 will be updated in-place
  ~ resource "adguard_client" "ina-vlan-30" {
        id                              = "NL-UTR-INA-VLAN-30"
      ~ last_updated                    = "Saturday, 30-Nov-24 20:34:53 CET" -> (known after apply)
        name                            = "NL-UTR-INA-VLAN-30"
      - tags                            = [] -> null
        # (14 unchanged attributes hidden)
    }

**Comment by gmichels** [comment]
The change is being triggered due to `tags` attribute going from an empty list `[]` to a `null` value. The `last_updated` attribute shows as changing because the resource is undergoing an update.

In order to better troubleshoot this, I need consistent reproduction steps. Do you have a way to reliably reproduce this behavior?

**Comment by gmichels** [comment]
I was trying to reproduce this issue and I believe I found something really odd that only happens when the remote ADG server is restarted. If I create a very simple client, such as:

```
resource "adguard_client" "test" {
  name = "Test Client"
  ids  = ["192.168.100.15", "test-client"]
}
```

I can run `apply` as many times I want, after the first creation the results are always there are no changes to be made. If I restart the ADG server and run `apply`, it prompts for updates:

```
Terraform will perform the following actions:

  # adguard_client.test will be updated in-place
  ~ resource "adguard_client" "test" {
      - blocked_services                = [] -> null
        id                              = "Test Client"
      ~ last_updated                    = "Thursday, 12-Dec-24 20:24:41 CST" -> (known after apply)
        name                            = "Test Client"
      - tags                            = [] -> null
      - upstreams                       = [] -> null
        # (12 unchanged attributes hidden)
    }
```

I can't explain why, it makes absolutely no sense since the ADG API response is exactly the same regardless if the remote server was restarted or not.

Still, I will see if I can find a way around it.
