### ISSUE TITLE
Error Fetching Valid Values for Blocked Services

### ISSUE THREAD

**Issue by headless-cross** [gmichels/terraform-provider-adguard#119]
Hello,

Thank you for your hard work on this provider. I'm encountering the following issue while creating an "adguard_rewrite" resource. Please consider the source code:

```
resource "adguard_rewrite" "test" {
    domain = "test.example.com"
    answer = "192.168.253.1"
}
```

and the configuration of the provider:
```
provider "adguard" {
    host     = "192.168.255.4"
    username = local.adguard.username
    password = local.adguard.password
    scheme   = "https" # or http, I've tried with different variations
    timeout  = 10
}
```

The error I'm getting is the following:

```
│ Error: Error Fetching Valid Values for Blocked Services
│
│   with provider["registry.terraform.io/gmichels/adguard"],
│   on providers.tf line 67, in provider "adguard":
│   67: provider "adguard" {
│
│ Could not fetch valid values from AdGuard Home
```

I would appreciate any input you can give me.

**Comment by gmichels** [comment]
Can you please tell the version of the provider that you are using? And if it ever worked for you (in which version)?

**Comment by gmichels** [comment]
Can you try with version 1.3.0? Version 1.4.0 had a change to pull the list of available blocked services dynamically from the ADG server at startup, as the list of available services changes at almost every ADG release.

If I were to guess, you will still see some other problem when using 1.3.0. Since you never used the provider, chances are you have something incorrect with your setup, but the error that you are seeing is likely misleading of that.
